Tokenendpoint Parameters [SDK-1730]
auth0/express-openid-connect pull request #228
Opened 2021-04-29 06:08 UTC by davidpatrick

## Description
Given I configure the SDK
When I add custom parameters to the tokenEndpointParams argument
Then those additional parameters are reflected in the oauth/token request for the code exchange

Given I configure the SDK
When I add custom parameters to the tokenEndpointParams argument
Then those additional parameters are reflected in the oauth/token request for the refresh grant

Given I configure the SDK
When I add custom parameters to the tokenEndpointParams argument
And I call req.oidc.accessToken.refresh({ params }) method with extra params
Then both the config and refresh argument params are passed to the token endpoint with the params argument taking precedence

2021-04-29 06:14 UTC, panva reviewed
Should we allow this to be specified dynamically with the request's context, e.g. with a function instead of a fixed set of properties?

2021-04-29 09:52 UTC, adamjmcgrath requested changes

2021-04-29 09:52 UTC, adamjmcgrath commented on index.d.ts
> +  tokenParameters?: {
`tokenEndpointParams`

You also need to update the signature for `refresh` https://github.com/auth0/express-openid-connect/blob/b73edb95455ad6a04b51290f18eb71db54d068cd/index.d.ts#L633

2021-04-29 09:52 UTC, adamjmcgrath commented on index.d.ts
> +   * Additional extra request body properties to be sent to the AS during code or refresh token exchange
```suggestion
   * Additional request body properties to be sent to the `oauth/token` endpoint during code exchange or token refresh.
```

2021-04-29 09:52 UTC, adamjmcgrath commented on lib/context.js
> +async function refresh(params) {
`refresh({ tokenEndpointParams })` Let's make this a config object and also call it `tokenEndpointParams`

2021-04-29 09:52 UTC, adamjmcgrath commented on test/callback.tests.js
> +        tokenEndpointParams: {
This shouldn't be nested in `authorizationParams` - which is why `longeLiveToken` isn't being passed to the token endpoint.

2021-04-29 09:52 UTC, adamjmcgrath commented on test/callback.tests.js
> +    const { tokens, jar } = await setup({
You can also get the `tokenReqBody` for the code exchange, then assert the `tokenEndpointParams` have been added there too.

```js
const { tokens, jar, tokenReqBody } = await setup({ ... });

assert.match(tokenReqBody, /longeLiveToken=true/);
```

2021-04-29 10:02 UTC, adamjmcgrath commented
@panva 

> Should we allow this to be specified dynamically with the request's context, e.g. with a function instead of a fixed set of properties?

Good point, I forgot about this

We don't do it with `authorizationParams` because you can customise the login handler and pass `authorizationParams` in depending on the request context.

```js
app.get('/login', (req, res) => {
  res.oidc.login({ authorizationParams: { ... something related to req ... } });
})
```

I'd quite like to resolve this when it comes up with `callback` and `tokenEndpointParams` as well, with the caveat that it's harder to overdide the callback

```js
// or `get`
app.post('/callback', express.urlencoded({ extended: false }), (req, res) => {
  res.oidc.callback({ tokenEndpointParams: { ... somthing related to req ... } });
});
```

2021-04-29 15:19 UTC, panva commented on index.d.ts
> +   * Additional request body properties to be sent to the `oauth/token` endpoint during code exchange or token refresh.
```suggestion
   * Additional request body properties to be sent to the `token_endpoint` during authorization code exchange or token refresh.
```

2021-04-30 09:12 UTC, adamjmcgrath commented on index.d.ts
> +  tokenParameters?: TokenParameters
`tokenEndpointParams`

2021-04-30 09:14 UTC, adamjmcgrath requested changes
just need to fix the type defs for `tokenEndpointParams`

2021-05-04 09:24 UTC, adamjmcgrath approved these changes

2021-05-05 07:30 UTC, merged